package `in`.iot.lab.teacherreview.feature_teacherlist.data.model

/**
 * This is the Structure of the Individual Faculty Data
 *
 * @param _id Auto Generated by the Server
 * @param name This is the name of the Faculty
 * @param avgRating Average Total Rating of the Teacher
 * @param avgTeachingRating Average Teaching Rating given to the Teacher
 * @param avgMarkingRating Average Marking rating given to the Teacher
 * @param avgAttendanceRating This is the average rating given to the Teacher
 */
data class IndividualFacultyData(
    val _id: String,
    val name: String = "",
    var avgRating: Double = 0.0,
    val avgTeachingRating: Double = 0.0,
    val avgMarkingRating: Double = 0.0,
    val avgAttendanceRating: Double = 0.0,
    val code: String? = null
)